# Configuración de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/RegistrosDT
spring.datasource.username=postgres
spring.datasource.password=1234

# Dialecto y comportamiento de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave Secreta y Expiración para JWT (Ejemplo: 8 horas = 28800000 ms)
jwt.secret=ProyectodePG1y2enDEMI_TOTONICAPAN_totonicapan2026!
jwt.expiration=28800000
